# Generated by Django 5.1.2 on 2024-11-18 01:14

import uuid
from django.db import migrations, models

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("Wrapped", "spotifywrap")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["id"])

class Migration(migrations.Migration):

    dependencies = [
        ('Wrapped', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifywrap',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
