# Generated by Django 5.1.2 on 2024-11-18 01:14

import uuid
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('Wrapped', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifywrap',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
