# Generated by Django 5.1.2 on 2024-11-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Wrapped", "0003_spotifywrap_likes_alter_follow_follower_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotifywrap",
            name="audio_features",
            field=models.TextField(default="{}"),
        ),
    ]
