# Generated by Django 5.1.2 on 2024-11-18 01:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wrapped', '0005_make_primary_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifywrap',
            name='id',
        ),
    ]
