# Generated by Django 5.1.2 on 2024-11-18 07:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wrapped', '0006_set_uuid_to_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifywrap',
            old_name='uuid',
            new_name='id',
        ),
    ]
