# Generated by Django 5.1.2 on 2024-11-30 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Wrapped", "0006_alter_spotifywrap_uuid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="spotifywrap",
            name="liked_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liked_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
