# Generated by Django 5.1.2 on 2024-11-18 07:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wrapped', '0007_remove_spotifywrap_uuid_spotifywrap_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifywrap',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
