# Generated by Django 5.1.2 on 2024-11-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifywrap',
            name='description',
        ),
        migrations.AddField(
            model_name='spotifywrap',
            name='artists',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='spotifywrap',
            name='tracks',
            field=models.TextField(default='[]'),
        ),
    ]
