# Generated by Django 5.1.2 on 2024-11-11 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_spotifywrap_description_spotifywrap_artists_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifywrap',
            name='artists',
        ),
        migrations.RemoveField(
            model_name='spotifywrap',
            name='tracks',
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('genres', models.JSONField()),
                ('image_url', models.URLField()),
                ('artist_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_range', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('album_name', models.CharField(max_length=255)),
                ('duration_ms', models.IntegerField()),
                ('song_url', models.URLField()),
                ('preview_url', models.URLField(blank=True, null=True)),
                ('album_image_url', models.URLField()),
                ('artist_url', models.URLField()),
                ('album_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_range', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='spotifywrap',
            name='artists',
            field=models.ManyToManyField(related_name='spotify_wraps', to='myapp.artist'),
        ),
        migrations.AddField(
            model_name='spotifywrap',
            name='tracks',
            field=models.ManyToManyField(related_name='spotify_wraps', to='myapp.track'),
        ),
    ]
