# Generated by Django 5.1.2 on 2024-11-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_spotifywrap_artists_remove_spotifywrap_tracks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifywrap',
            name='artists',
        ),
        migrations.RemoveField(
            model_name='track',
            name='user',
        ),
        migrations.RemoveField(
            model_name='spotifywrap',
            name='tracks',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.AddField(
            model_name='spotifywrap',
            name='artists',
            field=models.TextField(default='[]'),
        ),
        migrations.DeleteModel(
            name='Track',
        ),
        migrations.AddField(
            model_name='spotifywrap',
            name='tracks',
            field=models.TextField(default='[]'),
        ),
    ]
