# Generated by Django 5.1.2 on 2024-10-30 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifytoken',
            name='spotify_account_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spotifytoken',
            name='spotify_account_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
