# Generated by Django 5.1.2 on 2024-11-25 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserAuth", "0004_contactus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spotifytoken",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
