# Generated by Django 5.1.2 on 2024-10-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0006_alter_spotifytoken_session_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifytoken',
            name='session_id',
        ),
        migrations.AlterField(
            model_name='spotifytoken',
            name='user',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
